### ISSUE TITLE
Automatic long Git hash version

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/heads#4]
For the development and CI/CD purposes it would be nice to have each build extended with a file containing the long commit hash, which could be easily checked in the recovery shell or perhaps written in the system info.

**Comment by alex-nitrokey** [comment]
The git has is already stored as a variable in /tmp/config. I will use this for  [version info](https://github.com/Nitrokey/heads/blob/a0753473510ec598f9db86cfb610cf61156ca5cb/initrd/bin/gui-init#L396).

Furthermore, I want to adapt the Makefile to just append the hash to each build-file, so that they are unique and not all called `coreboot.rom`. Does this sound like a good solution to you?

**Comment by szszszsz** [comment]
Ok!
Something like `coreboot-<version>.rom`? That would be nice.

**Comment by alex-nitrokey** [comment]
Done [here](https://github.com/osresearch/heads/commit/a7533b28e1192dc301dc1c019cdce5e5b43af320).

**Comment by szszszsz** [comment]
Looks good!

**Comment by alex-nitrokey** [comment]
Fixed in [`v1.2`](https://github.com/Nitrokey/heads/releases/tag/v1.2)
